### ISSUE TITLE
[iOS]license and data usage missing in about page

### ISSUE THREAD

**Issue by dipsywong98** [USThing/USThing_Master#244] opened 2018-04-17 10:24 UTC
### Expected behavior
refer to android
### Actual behavior
license and data usage missing in about
### Steps to reproduce
homepage ->Top right hand icon -> about ->scroll to bottom

### Environment
- App Version: most recent release
- Phone Model:iPhone7
- OS Version: iOS
- OS Language:English 

Found by @mcreng

**Comment by chihimng** [comment] 2018-04-17 10:28
Duplicate of https://github.com/USThing/USThing_Master/issues/213
Thanks for reporting.

**Closed by chihimng** 2018-04-17 10:28 UTC

**Comment by mcreng** [comment] 2018-04-17 10:42
There exists no ‘License Agreement’ tab in App Store. 
![Image](https://i.imgur.com/d8tpDiq.jpg)

**Comment by chihimng** [comment] 2018-04-17 10:46
@mcreng Please refer to Apple's standard EULA, https://www.apple.com/legal/internet-services/itunes/dev/stdeula/, which you accepts when downloading our app from the App Store.
