### ISSUE TITLE
[Grade] Year 1 Transferred Credits Not Showing in GGA Estimation

### ISSUE THREAD

**Issue by klwuco** [USThing/USThing_Master#260] opened 2018-06-08 15:09 UTC
### Expected behavior
As I have more than 10 transferred credits, it should show up in GGA Estimation feature in "Grades", and the weighting should show up as one; same goes for the calculation of GGA

### Actual behavior
Part of the text in text box:
""" **GGA Estimation**
Year 1 Transferred Credits: 0.000
Year 1 Weighting: 0.5
[...]"""

### Steps to reproduce
0. (Have credit transfer on entry)
1. Go on to Grades -> GGA Estimation

### Environment
- App Version: 3.40
- Phone Model: ASUS Zenfone 4
- OS Version: Android 8.0.0
- OS Language: Traditional Chinese

**Comment by chihimng** [comment] 2018-07-10 06:33
duplicate of #110

**Closed by chihimng** 2018-07-10 06:33 UTC
Labels: android, bug
